# Generated by Django 5.0.7 on 2026-05-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255, verbose_name='Проблема')),
                ('causes', models.TextField(verbose_name='Причины')),
                ('solution', models.TextField(verbose_name='Решение')),
                ('skus', models.JSONField(blank=True, default=list, verbose_name='SKU')),
                ('restrictions', models.TextField(blank=True, verbose_name='Ограничения')),
                ('approving_expert', models.CharField(max_length=255, verbose_name='Эксперт')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'База знаний',
                'ordering': ('problem',),
            },
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ('company_name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ('name',), 'verbose_name': 'Дистрибьютор', 'verbose_name_plural': 'Дистрибьюторы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',), 'verbose_name': 'Магазин / точка', 'verbose_name_plural': 'Магазины / точки'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='category',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='b', max_length=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(max_length=128, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='contact_name',
            field=models.CharField(max_length=255, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='api.distributor', verbose_name='Дистрибьютор'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='partner_status',
            field=models.CharField(default='Silver', max_length=32, verbose_name='Партнёрский статус'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='region',
            field=models.CharField(max_length=128, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='status',
            field=models.CharField(choices=[('newClient', 'Новый'), ('pending', 'На проверке'), ('active', 'Активный'), ('blocked', 'Заблокирован'), ('archived', 'Архив')], default='active', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма закупок'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='regions',
            field=models.JSONField(blank=True, default=list, verbose_name='Регионы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.clientprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.distributor', verbose_name='Дистрибьютор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Новый'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('done', 'Выполнен')], default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.store', verbose_name='Где забрать'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='store',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='api.clientprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ColorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=128, verbose_name='Марка')),
                ('car_model', models.CharField(max_length=128, verbose_name='Модель')),
                ('vin', models.CharField(max_length=32, verbose_name='VIN')),
                ('color_code', models.CharField(max_length=64, verbose_name='Код цвета')),
                ('color_name', models.CharField(blank=True, max_length=128, verbose_name='Название цвета')),
                ('urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('courier_pickup', models.BooleanField(default=False, verbose_name='Нужен курьер для лючка')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('inProgress', 'В работе'), ('ready', 'Готова'), ('delivered', 'Выдана')], default='created', max_length=32, verbose_name='Статус')),
                ('recipe', models.TextField(blank=True, verbose_name='Рецепт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_requests', to='api.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка на колеровку',
                'verbose_name_plural': 'Колеровка',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourierTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Забор лючка'), ('return', 'Возврат лючка')], default='delivery', max_length=32, verbose_name='Тип')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('scheduled_time', models.DateTimeField(verbose_name='Время')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Контакт')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('car_description', models.CharField(blank=True, max_length=255, verbose_name='Авто/описание')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначен курьер'), ('inProgress', 'В пути'), ('delivered', 'Доставлено'), ('returned', 'Возвращено')], default='created', max_length=32, verbose_name='Статус')),
                ('courier_id', models.CharField(blank=True, max_length=128, verbose_name='Курьер')),
                ('photo_proof', models.CharField(blank=True, max_length=255, verbose_name='Фото')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_tasks', to='api.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
                'ordering': ('-scheduled_time',),
            },
        ),
        migrations.CreateModel(
            name='ExpertTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
                ('ai_answer', models.TextField(blank=True, verbose_name='Ответ AI')),
                ('expert_answer', models.TextField(blank=True, verbose_name='Ответ эксперта')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('aiAnswered', 'Ответ AI'), ('escalated', 'Передан эксперту'), ('expertAnswered', 'Ответ эксперта'), ('closed', 'Закрыт')], default='open', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_tickets', to='api.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Вопрос эксперту',
                'verbose_name_plural': 'Вопросы эксперту',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(choices=[('order', 'Заказ'), ('color', 'Колеровка'), ('delivery', 'Доставка'), ('referral', 'Реферал'), ('ai', 'AI'), ('system', 'Система')], default='system', max_length=32, verbose_name='Тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
                ('brand', models.CharField(default='AutoTerra', max_length=128, verbose_name='Бренд')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Объём')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('status', models.CharField(choices=[('inStock', 'В наличии'), ('low', 'Мало'), ('onOrder', 'Под заказ'), ('outOfStock', 'Нет в наличии')], default='inStock', max_length=32, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в приложении')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.distributor', verbose_name='Дистрибьютор')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Ассортимент',
                'ordering': ('category', 'name'),
                'unique_together': {('distributor', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
                ('brand', models.CharField(max_length=128, verbose_name='Бренд')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Объём')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=128, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('verified', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=32, verbose_name='Статус')),
                ('document_url', models.CharField(blank=True, max_length=255, verbose_name='Файл/ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.clientprofile', verbose_name='Клиент')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='api.distributor', verbose_name='Дистрибьютор')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Объём')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('brand', models.CharField(default='AutoTerra', max_length=128, verbose_name='Бренд')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchase', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Позиция покупки',
                'verbose_name_plural': 'Позиции покупки',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_inn', models.CharField(max_length=12, verbose_name='ИНН приглашённого')),
                ('invitee_name', models.CharField(max_length=255, verbose_name='Название приглашённого')),
                ('region', models.CharField(max_length=128, verbose_name='Регион')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('has_purchase', models.BooleanField(default=False, verbose_name='Есть покупка')),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма покупки')),
                ('condition_met', models.BooleanField(default=False, verbose_name='Условие выполнено')),
                ('gift', models.CharField(blank=True, max_length=255, verbose_name='Подарок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.clientprofile', verbose_name='Кто пригласил')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'ordering': ('-created_at',),
            },
        ),
    ]
