# Generated by Django 5.0.7 on 2026-05-17 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_knowledgecard_alter_clientprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт дистрибьютора'),
        ),
    ]
