# Generated by Django 5.0.7 on 2026-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_distributor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, verbose_name='Артикул'),
        ),
    ]
