# Generated by Django 5.2.6 on 2026-06-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_courier_task_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU/Material')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(default='g', max_length=16, verbose_name='Единица измерения')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия рецепта')),
            ],
            options={
                'verbose_name': 'Материал рецепта',
                'verbose_name_plural': 'Материалы рецепта',
                'ordering': ('version', 'id'),
            },
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='api_attachm_content_3fcb3e_idx',
            old_name='api_attachm_content_21f603_idx',
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='assigned_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_color_requests', to='api.distributor', verbose_name='Назначенный дистрибьютор'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='assigned_station',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назначенная станция'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='car_year',
            field=models.CharField(blank=True, max_length=4, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='delivery_method',
            field=models.CharField(default='courier', max_length=64, verbose_name='Способ передачи'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес забора лючка'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время забора'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA deadline'),
        ),
        migrations.AddField(
            model_name='colorrequest',
            name='status_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История статусов'),
        ),
        migrations.AddField(
            model_name='recipematerial',
            name='color_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.colorrequest', verbose_name='Заявка'),
        ),
    ]
