# Generated by Django 5.2.6 on 2026-06-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recipematerial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgecard',
            options={'ordering': ('-created_at',), 'verbose_name': 'База знаний', 'verbose_name_plural': 'База знаний'},
        ),
        migrations.AddField(
            model_name='expertticket',
            name='ai_draft_answer',
            field=models.TextField(blank=True, verbose_name='AI черновик ответа'),
        ),
        migrations.AddField(
            model_name='expertticket',
            name='linked_knowledge_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tickets', to='api.knowledgecard', verbose_name='Связанная база знаний'),
        ),
        migrations.AddField(
            model_name='expertticket',
            name='risk',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16, verbose_name='Риск'),
        ),
        migrations.AddField(
            model_name='expertticket',
            name='similar_cases',
            field=models.JSONField(blank=True, default=list, verbose_name='Похожие кейсы'),
        ),
        migrations.AddField(
            model_name='expertticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='expertticket',
            name='ai_answer',
            field=models.TextField(blank=True, verbose_name='Ответ AI (опубликованный)'),
        ),
    ]
