# Generated by Django 5.2.6 on 2026-06-04 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_knowledgecard_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgecard',
            name='approving_expert',
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='category',
            field=models.CharField(blank=True, max_length=128, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='revision_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История правок'),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'Архив')], default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='knowledgecard',
            name='causes',
            field=models.TextField(blank=True, verbose_name='Причины'),
        ),
        migrations.AlterField(
            model_name='knowledgecard',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено (legacy)'),
        ),
    ]
