# Generated by Django 5.2.6 on 2026-06-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_knowledgecard_approving_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Внешний ID (1C)'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Внешний ID (1C)'),
        ),
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Внешний ID (1C)'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Внешний ID (1C)'),
        ),
    ]
