# Generated by Django 5.2.6 on 2026-06-05 12:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_clientprofile_external_id_distributor_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='api.distributor', verbose_name='Дистрибьютор'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен состоять из 10 или 12 цифр.', regex='^\\d{10}(\\d{2})?$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='api.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='registration_source',
            field=models.CharField(choices=[('app', 'Мобильное приложение'), ('web', 'Веб-сайт'), ('manager', 'Менеджер')], default='app', max_length=32, verbose_name='Источник регистрации'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('under_review', 'На проверке'), ('active', 'Активный'), ('blocked', 'Заблокирован')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='region',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_regions', to='api.distributor', verbose_name='Дистрибьютор'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Клиент (автосервис)'), ('distributor', 'Дистрибьютор'), ('manager', 'Менеджер импортера'), ('admin', 'Центральный админ'), ('courier', 'Курьер'), ('ai_expert', 'Эксперт базы знаний')], default='client', max_length=20, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
