# Generated by Django 5.2.6 on 2026-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_clientprofile_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('pending', 'На проверке'), ('pending_verification', 'Ожидает подтверждения'), ('under_review', 'Ручная проверка'), ('duplicate_review', 'Проверка дубля'), ('verified', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending_verification', max_length=32, verbose_name='Статус'),
        ),
    ]
