# Generated by Django 5.2.6 on 2026-06-05 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_purchase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couriertask',
            options={'ordering': ('-created_at',), 'verbose_name': 'Задача курьера', 'verbose_name_plural': 'Задачи курьеров'},
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='assigned_courier',
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='car_description',
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='courier_id',
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='photo_proof',
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='couriertask',
            name='type',
        ),
        migrations.AddField(
            model_name='couriertask',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='couriertask',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='courier_proofs/%Y/%m/', verbose_name='Фото-подтверждение'),
        ),
        migrations.AddField(
            model_name='couriertask',
            name='task_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Забор лючка'), ('return', 'Возврат лючка')], default='delivery', max_length=32, verbose_name='Тип задачи'),
        ),
        migrations.AddField(
            model_name='couriertask',
            name='time_slot',
            field=models.CharField(default=1, max_length=64, verbose_name='Временной интервал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couriertask',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначен'), ('in_progress', 'В пути'), ('delivered', 'Доставлено'), ('returned', 'Возвращено'), ('cancelled', 'Отменено')], default='assigned', max_length=32, verbose_name='Статус'),
        ),
    ]
