# Generated by Django 5.2.8 on 2026-06-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_couriertask_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couriertask",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Задача курьера",
                "verbose_name_plural": "Задачи курьера",
            },
        ),
        migrations.RenameField(
            model_name="colorrequest",
            old_name="pickup_date",
            new_name="pickup_time",
        ),
        migrations.RemoveField(
            model_name="colorrequest",
            name="courier_pickup",
        ),
        migrations.RemoveField(
            model_name="colorrequest",
            name="delivery_method",
        ),
        migrations.AddField(
            model_name="colorrequest",
            name="transfer_method",
            field=models.CharField(
                choices=[("courier", "Курьер"), ("self_delivery", "Сам привезу")],
                default="courier",
                max_length=32,
                verbose_name="Способ передачи",
            ),
        ),
        migrations.AddField(
            model_name="couriertask",
            name="car_description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Автомобиль"
            ),
        ),
        migrations.AddField(
            model_name="couriertask",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Контактное лицо"
            ),
        ),
        migrations.AddField(
            model_name="couriertask",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="couriertask",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Запланировано"
            ),
        ),
        migrations.AlterField(
            model_name="couriertask",
            name="proof_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courier_proofs/%Y/%m/",
                verbose_name="Фото-отчет",
            ),
        ),
        migrations.AlterField(
            model_name="couriertask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("delivery", "Доставка"),
                    ("pickup", "Забор лючка"),
                    ("return", "Возврат лючка"),
                    ("color_lab_pickup", "Забор для Color Lab"),
                ],
                default="delivery",
                max_length=32,
                verbose_name="Тип задачи",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("accepted", "Принят"),
                    ("rejected", "Отклонён"),
                    ("fulfilled", "Выполнен"),
                ],
                default="new",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
