# Generated by Django 5.2.8 on 2026-06-06 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_couriertask_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgecard",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="knowledgecard",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="knowledgecard",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="expertticket",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tickets/photos/%Y/%m/",
                verbose_name="Фото дефекта",
            ),
        ),
        migrations.AddField(
            model_name="expertticket",
            name="video_link",
            field=models.URLField(blank=True, verbose_name="Ссылка на видео"),
        ),
        migrations.AddField(
            model_name="knowledgecard",
            name="expert_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_knowledge_cards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор-эксперт",
            ),
        ),
        migrations.AddField(
            model_name="knowledgecard",
            name="source_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_knowledge_cards",
                to="api.expertticket",
                verbose_name="Источник (тикет)",
            ),
        ),
        migrations.AlterField(
            model_name="expertticket",
            name="linked_knowledge_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_tickets_legacy",
                to="api.knowledgecard",
                verbose_name="Связанная база знаний",
            ),
        ),
    ]
