# Generated by Django 5.2.6 on 2026-06-06 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_link",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ссылка"),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications_legacy",
                to="api.clientprofile",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "Информация"),
                    ("action_required", "Требуется действие"),
                    ("recommendation", "Рекомендация"),
                    ("order", "Заказ"),
                    ("color", "Колеровка"),
                    ("delivery", "Доставка"),
                    ("referral", "Реферал"),
                    ("ai", "AI"),
                    ("system", "Система"),
                ],
                default="info",
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
