# Generated by Django 5.2.6 on 2026-06-06 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_notification_related_link_notification_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=128, unique=True, verbose_name="Токен"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_tokens",
                        to="api.distributor",
                        verbose_name="Дистрибьютор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен интеграции",
                "verbose_name_plural": "Токены интеграции",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("stock_update", "Обновление остатков"),
                            ("orders_export", "Экспорт заказов"),
                        ],
                        max_length=32,
                        verbose_name="Тип синхронизации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успех"), ("error", "Ошибка")],
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Детали"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата/время"),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="api.distributor",
                        verbose_name="Дистрибьютор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог синхронизации",
                "verbose_name_plural": "Логи синхронизации",
                "ordering": ("-created_at",),
            },
        ),
    ]
