# Generated by Django 5.2.6 on 2026-06-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_integrationtoken_synclog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertticket',
            name='expert_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ответивший эксперт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специализация'),
        ),
    ]
