# Generated by Django 5.2.6 on 2026-06-08 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_order_store"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Курьер",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ожидаемая дата доставки"
            ),
        ),
    ]
