# Generated by Django 5.2.6 on 2026-06-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_order_courier_order_estimated_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("courier", "Курьерская доставка"),
                    ("self_pickup", "Самовывоз"),
                ],
                default="courier",
                max_length=32,
                verbose_name="Способ получения",
            ),
        ),
    ]
