# Generated by Django 5.2.6 on 2026-06-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_order_delivery_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couriertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("assigned", "Назначен"),
                    ("in_progress", "В пути"),
                    ("delivered", "Доставлено"),
                    ("returned", "Возвращено"),
                    ("cancelled", "Отменено"),
                ],
                default="created",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
