# Generated by Django 5.2.6 on 2026-06-16 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_managertask_contacthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managertask",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_tasks",
                to="api.clientprofile",
                verbose_name="Клиент",
            ),
        ),
    ]
