# Generated by Django 5.2.6 on 2026-07-21 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_repair_all_decimals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Подтверждён"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Оплачен"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Отправлен"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("confirmed", "Подтверждён"),
                    ("adjusted", "Скорректирован"),
                    ("accepted", "Принят"),
                    ("rejected", "Отклонён"),
                    ("paid", "Оплачен"),
                    ("shipped", "Отправлен"),
                    ("fulfilled", "Выполнен"),
                    ("cancelled", "Отменён"),
                ],
                default="new",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="OrderAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_items",
                    models.JSONField(default=list, verbose_name="Изначальные позиции"),
                ),
                (
                    "adjusted_items",
                    models.JSONField(
                        default=list, verbose_name="Подтверждённые позиции"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Комментарий оператора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто скорректировал",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="api.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корректировка заказа",
                "verbose_name_plural": "Корректировки заказов",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="yookassa", max_length=32, verbose_name="Провайдер"
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="ID платежа у провайдера",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=8, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("waiting_for_capture", "Ожидает подтверждения"),
                            ("succeeded", "Оплачен"),
                            ("canceled", "Отменён"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "confirmation_url",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="Ссылка на оплату"
                    ),
                ),
                (
                    "idempotence_key",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ провайдера"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Оплачен"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ("-created_at",),
            },
        ),
    ]
