# Generated by Django 5.2.6 on 2026-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_order_confirmed_at_order_paid_at_order_shipped_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Баркод"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=128, verbose_name="Цвет"),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="group_name",
            field=models.CharField(blank=True, max_length=128, verbose_name="Группа"),
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Фото (ссылки)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_height",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Высота упаковки (см)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_length",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Длина упаковки (см)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_width",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Ширина упаковки (см)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tnved",
            field=models.CharField(blank=True, max_length=32, verbose_name="ТНВЭД"),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Ставка НДС"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, max_length=512, verbose_name="Видео"),
        ),
        migrations.AddField(
            model_name="product",
            name="wb_article",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Артикул WB"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=8,
                verbose_name="Вес с упаковкой (кг)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=64, verbose_name="Артикул продавца"),
        ),
    ]
