# Generated by Django 5.2.6 on 2026-07-28 06:15

import api.models
from django.db import migrations, models


def normalize_existing_images(apps, schema_editor):
    """Приводит уже загруженные фото к новому формату: ≤ 15 http(s)-ссылок."""
    Product = apps.get_model("api", "Product")
    for product in Product.objects.exclude(images=[]).iterator():
        normalized = api.models.normalize_product_images(product.images)
        if normalized != product.images:
            Product.objects.filter(pk=product.pk).update(images=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_product_barcode_product_color_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список http(s)-ссылок на фото, максимум 15 шт. В Excel — одной ячейкой через «;».",
                validators=[api.models.validate_product_images],
                verbose_name="Фото (ссылки)",
            ),
        ),
        migrations.RunPython(normalize_existing_images, migrations.RunPython.noop),
    ]
