# Generated by Django 5.2.6 on 2026-07-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorrequest",
            name="courier_arrive_until",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Курьер может приехать до"
            ),
        ),
    ]
