# Generated by Django 5.2.6 on 2026-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_colorrequest_courier_arrive_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couriertask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("delivery", "Доставка"),
                    ("pickup", "Забор лючка"),
                    ("color_lab_pickup", "Забор для Color Lab"),
                ],
                default="delivery",
                max_length=32,
                verbose_name="Тип задачи",
            ),
        ),
    ]
