# Generated by Django 5.2.6 on 2026-07-29 14:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_couriertask_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="category",
            field=models.CharField(
                choices=[
                    ("a", "A · Дилерский салон"),
                    ("b", "B · Автосервис с кузовным цехом"),
                    ("c", "C · Гаражный сервис"),
                ],
                default="b",
                max_length=1,
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="RankDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_category",
                    models.CharField(
                        choices=[
                            ("a", "A · Дилерский салон"),
                            ("b", "B · Автосервис с кузовным цехом"),
                            ("c", "C · Гаражный сервис"),
                        ],
                        max_length=1,
                        verbose_name="Ранг клиента",
                    ),
                ),
                (
                    "product_category",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — скидка на весь ассортимент",
                        max_length=128,
                        verbose_name="Категория товаров",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка, %",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — правило действует у всех дистрибьюторов",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_discounts",
                        to="api.distributor",
                        verbose_name="Дистрибьютор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка по рангу",
                "verbose_name_plural": "Скидки по рангам",
                "ordering": ("client_category", "product_category"),
                "unique_together": {
                    ("distributor", "client_category", "product_category")
                },
            },
        ),
    ]
