# Generated by Django 5.2.6 on 2026-07-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_partnertier_rankdiscount_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="partner_status",
            field=models.CharField(
                default="Базовый",
                help_text="Присваивается автоматически по обороту. Менеджер может выставить вручную.",
                max_length=32,
                verbose_name="Ранг",
            ),
        ),
    ]
