# Generated by Django 5.2.15 on 2026-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_clientprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorrequest',
            name='paint_type',
            field=models.CharField(choices=[('acrylic', 'Акрил'), ('baseClear', 'База + лак'), ('threeStage', 'Трёхстадийная')], default='baseClear', max_length=32, verbose_name='Тип покрытия'),
        ),
    ]
