# Generated by Django 5.2.6 on 2026-08-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_gifts(apps, _schema_editor):
    """Уже выданные подарки не отправляем на согласование задним числом.

    Клиент их уже увидел в приложении; перевод в «ждёт согласования» выглядел
    бы как отзыв подарка. Согласование действует для новых условий.
    """
    Referral = apps.get_model("api", "Referral")
    Referral.objects.filter(condition_met=True).update(gift_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_colorrequest_paint_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="gift_comment",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Комментарий к решению"
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="gift_decided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда решено"
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="gift_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral_gift_decisions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто решил",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="gift_status",
            field=models.CharField(
                choices=[
                    ("none", "Условие не выполнено"),
                    ("pending", "Ждёт согласования"),
                    ("approved", "Согласован"),
                    ("declined", "Отклонён"),
                ],
                default="none",
                max_length=16,
                verbose_name="Согласование подарка",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("under_review", "На проверке"),
                    ("active", "Активный"),
                    ("blocked", "Заблокирован"),
                    ("archived", "Архивный"),
                ],
                default="new",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lesson", "Урок"),
                            ("checklist", "Чек-лист"),
                            ("video", "Видео"),
                            ("manual", "Инструкция"),
                            ("webinar", "Запись вебинара"),
                        ],
                        default="lesson",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Категория"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Краткое описание"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Содержание")),
                (
                    "video_url",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="Ссылка на файл"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Длительность, мин"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликован"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обучающий материал",
                "verbose_name_plural": "Обучающие материалы",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RunPython(grandfather_existing_gifts, migrations.RunPython.noop),
    ]
