# Generated by Django 5.2.6 on 2026-08-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_referral_gift_comment_referral_gift_decided_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="gift_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Номинал подарка",
            ),
        ),
        migrations.CreateModel(
            name="BonusTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("referral", "Начислен по реферальной программе"),
                            ("order", "Списан в счёт заказа"),
                            ("refund", "Возвращён после отмены оплаты"),
                            ("manual", "Ручная корректировка"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_transactions",
                        to="api.clientprofile",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_transactions",
                        to="api.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_transactions",
                        to="api.referral",
                        verbose_name="Реферал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция по бонусам",
                "verbose_name_plural": "Операции по бонусам",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "referral")),
                        fields=("referral",),
                        name="unique_referral_bonus_credit",
                    )
                ],
            },
        ),
    ]
