# Generated by Django 5.2.6 on 2026-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_referral_gift_amount_bonustransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorrequest",
            name="paint_type_note",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Уточнение по покрытию"
            ),
        ),
        migrations.AlterField(
            model_name="colorrequest",
            name="car_model",
            field=models.CharField(blank=True, max_length=128, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="colorrequest",
            name="vin",
            field=models.CharField(blank=True, max_length=32, verbose_name="VIN"),
        ),
    ]
