# Generated by Django 5.2.6 on 2026-08-06 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_colorrequest_paint_type_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.UniqueConstraint(
                fields=("inviter", "invitee_inn"),
                name="referral_unique_inviter_invitee",
            ),
        ),
    ]
