# Generated by Django 5.2.6 on 2026-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_referral_referral_unique_inviter_invitee"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="confirmation",
            field=models.CharField(
                choices=[
                    ("auto", "По реферальному коду"),
                    ("pending", "Ждёт подтверждения приглашённого"),
                    ("confirmed", "Приглашённый подтвердил"),
                    ("declined", "Приглашённый отказался"),
                ],
                default="auto",
                max_length=16,
                verbose_name="Подтверждение приглашённым",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда подтверждено"
            ),
        ),
    ]
