# Generated by Django 5.2.6 on 2026-08-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_referral_confirmation_referral_confirmed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonustransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("referral", "Начислен по реферальной программе"),
                    ("order", "Списан в счёт заказа"),
                    ("refund", "Возвращён после отмены оплаты"),
                    ("expired", "Сгорел из-за неактивности"),
                    ("manual", "Ручная корректировка"),
                ],
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
