# Generated by Django 5.2.6 on 2026-08-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_bonustransaction_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bonustransaction",
            name="unique_referral_bonus_credit",
        ),
    ]
