# Generated by Django 5.2.6 on 2026-10-02 10:29

from django.db import migrations, models


def backfill_reservations(apps, schema_editor):
    Order = apps.get_model('api', 'Order')
    Item = apps.get_model('api', 'OrderItem')
    Order.objects.filter(status__in=['cancelled', 'rejected']).update(stock_restored=True)
    Item.objects.filter(order__status__in=['new', 'confirmed', 'adjusted', 'accepted']).exclude(product__status='onOrder').update(reserved_quantity=models.F('quantity'))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_bonustransaction_unique_referral_bonus_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_reservations, migrations.RunPython.noop),
    ]
