# Generated by Django 5.2.17 on 2026-10-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_order_stock_reservations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPickedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picked_order_items', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_confirmations', to='api.orderitem')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_items', to='api.couriertask')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'order_item'), name='unique_courier_picked_item')],
            },
        ),
    ]
