# Generated by Django 5.2.17 on 2026-10-05 21:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_courierpickeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Персональная цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='api.clientprofile', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_price_overrides', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Персональная цена',
                'verbose_name_plural': 'Персональные цены',
                'constraints': [models.UniqueConstraint(fields=('client', 'product'), name='unique_client_product_price'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='client_price_positive')],
            },
        ),
    ]
