# Generated by Django 5.2.17 on 2026-10-06 03:44

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_client_price_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='personal_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Не задана — скидка по рангу; 0 — явно без скидки по рангу.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Персональная скидка, %'),
        ),
        migrations.AddConstraint(
            model_name='clientprofile',
            constraint=models.CheckConstraint(condition=models.Q(('personal_discount_percent__isnull', True), models.Q(('personal_discount_percent__gte', 0), ('personal_discount_percent__lte', 100)), _connector='OR'), name='client_personal_discount_range'),
        ),
    ]
