# Generated by Django 5.2.17 on 2026-10-06 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_client_personal_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='cash_payment_allowed',
            field=models.BooleanField(default=False, verbose_name='Разрешить оплату наличными курьеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collected_orders', to=settings.AUTH_USER_MODEL, verbose_name='Наличные получил'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн'), ('cash', 'Наличными курьеру')], default='online', max_length=16, verbose_name='Способ оплаты'),
        ),
    ]
