# Generated by Django 5.2.17 on 2026-10-07 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_cash_payment_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YooKassaRegistryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.distributor')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YooKassaRegistryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('kind', models.CharField(choices=[('payment', 'Платёж'), ('refund', 'Возврат')], max_length=16)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('provider_refund_id', models.CharField(blank=True, max_length=128)),
                ('order_id_hint', models.PositiveBigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='RUB', max_length=8)),
                ('fingerprint', models.CharField(max_length=64)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.distributor')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registry_operations', to='api.payment')),
                ('registry_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='api.yookassaregistryimport')),
            ],
        ),
    ]
