# Generated by Django 5.2.17 on 2026-10-07 12:52

from django.db import migrations, models


def backfill_search_text(apps, schema_editor):
    Product = apps.get_model("api", "Product")
    alias = schema_editor.connection.alias
    batch = []
    for product in Product.objects.using(alias).all().iterator(chunk_size=500):
        product.search_text = "\n".join(
            " ".join(str(value or "").casefold().replace("ё", "е").split())
            for value in (product.name, product.sku, product.brand, product.category)
        )
        batch.append(product)
        if len(batch) == 500:
            Product.objects.using(alias).bulk_update(batch, ["search_text"])
            batch = []
    if batch:
        Product.objects.using(alias).bulk_update(batch, ["search_text"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_yookassa_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_text',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='synonyms',
            field=models.JSONField(blank=True, default=list, help_text='Список альтернативных названий, например ["пленка", "укрывной материал"]. В Excel — через «;».', verbose_name='Синонимы'),
        ),
        migrations.RunPython(backfill_search_text, migrations.RunPython.noop),
    ]
