# Generated by Django 5.2.17 on 2026-10-08 12:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_product_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Информационная цена продажи; не влияет на закупку и оплату.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='Наценка магазина, %'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='category',
            field=models.CharField(choices=[('a', 'A · Дилерский салон'), ('b', 'B · Автосервис с кузовным цехом'), ('c', 'C · Гаражный сервис'), ('s', 'Магазин')], default='b', max_length=1, verbose_name='Категория'),
        ),
    ]
