from django.urls import path

from . import schema, views

urlpatterns = [
    path("docs/", schema.swagger_ui),
    path("schema/", schema.openapi_schema),
    path("health/", views.health),
    path("register/", views.register),
    path("auth/register/", views.register),
    path("auth/password-reset/", views.password_reset),
    path("login/", views.login),
    path("me/", views.me),
    path("auth/me/", views.me),
    path("dashboard/", views.dashboard),
    path("stores/", views.stores),
    path("stores/<int:store_id>/", views.store_detail),
    path("products/", views.products),
    path("order-config/", views.order_config),
    path("orders/", views.orders),
    path("orders/create/", views.create_order),
    path("orders/<int:order_id>/", views.order_detail),
    path("orders/<int:order_id>/cancel/", views.cancel_order),
    # Безопасный поток заказа
    path("orders/<int:order_id>/confirm/", views.confirm_order),          # оператор
    path("orders/<int:order_id>/adjust/", views.adjust_order),            # оператор
    path("orders/<int:order_id>/reject/", views.reject_order),            # оператор
    path("orders/<int:order_id>/ship/", views.ship_order),                # оператор
    path("orders/<int:order_id>/accept-adjustment/", views.accept_adjustment),  # клиент
    path("orders/<int:order_id>/pay/", views.pay_order),                  # клиент
    # Webhook от YooKassa (без авторизации, вызывается платёжной системой)
    path("payments/yookassa/webhook/", views.yookassa_webhook),
    path("purchases/", views.purchases),
    path("purchases/create/", views.create_purchase),
    path("manager/dashboard/", views.manager_dashboard),
    path("manager/clients/", views.manager_clients),
    path("manager/clients/<int:client_id>/unified/", views.manager_client_unified),
    path("manager/clients/<int:client_id>/status/", views.manager_client_status),
    path("manager/clients/<int:client_id>/history/", views.manager_client_history),
    path("manager/tasks/", views.manager_tasks),
    path("manager/tasks/<int:task_id>/", views.manager_update_task),
    path("reports/export/", views.export_excel),
    path("integration/erp/stock-update/", views.erp_stock_update),
    path("integration/erp/catalog-sync/", views.erp_catalog_sync),
    path("integration/erp/client-sync/", views.erp_client_sync),
    path("integration/erp/orders-export/", views.erp_orders_export),
    path("integration/1c/exchange/", views.erp_1c_exchange),
    path("admin/integration/tokens/", views.admin_integration_tokens),
    path("admin/integration/generate/<int:distributor_id>/", views.admin_integration_generate),
    path("admin/integration/logs/", views.admin_integration_logs),
    path("admin/analytics/", views.admin_analytics),
    path("admin/managers/", views.admin_managers),
    path("admin/manager-tasks/", views.admin_manager_tasks),
    path("admin/manager-tasks/<int:task_id>/", views.admin_manager_task_detail),
    path("admin/managers/<int:manager_id>/clients/", views.admin_manager_clients),
    path("distributor/couriers/", views.distributor_couriers),
    path("distributor/dashboard/", views.distributor_dashboard),
    path("distributor/clients/", views.distributor_clients),
    # Выгрузка списка клиентов в файл: доступна дистрибьютору, менеджеру
    # региона и главному менеджеру — каждому в своём объёме.
    path("clients/export/", views.export_clients_file),
    path("distributor/purchases/", views.distributor_purchases),
    path("distributor/purchases/<int:purchase_id>/verify/", views.distributor_verify_purchase),
    path("distributor/orders/", views.distributor_orders),
    path("distributor/orders/<int:order_id>/status/", views.distributor_update_order_status),
    path("distributor/color-requests/", views.distributor_color_requests),
    path("distributor/color-requests/<int:request_id>/status/", views.distributor_update_color_request),
    path("distributor/delivery-tasks/", views.distributor_delivery_tasks),
    path("distributor/delivery-tasks/<int:task_id>/status/", views.distributor_update_delivery_status),
    path("distributor/integration/", views.distributor_integration_token),
    path("distributor/integration/generate/", views.distributor_integration_generate),
    path("distributor/stock/", views.distributor_stock),
    path("distributor/stock/add/", views.distributor_add_product),
    path("distributor/stock/upload/", views.distributor_stock_upload),
    path("distributor/stock/upload-file/", views.distributor_stock_upload_file),
    path("distributor/reports/", views.distributor_reports),
    path("color-requests/", views.color_requests),
    path("color-requests/create/", views.create_color_request),
    path("color-requests/<int:request_id>/cancel/", views.cancel_color_request),
    path("color-requests/<int:request_id>/update/", views.update_color_request),
    path("courier-tasks/", views.courier_tasks),
    path("courier-tasks/create/", views.create_courier_task),
    path("courier-tasks/<int:task_id>/cancel/", views.cancel_courier_task),
    path("courier-tasks/<int:task_id>/update/", views.update_courier_task),
    path("courier-tasks/<int:task_id>/proof/", views.courier_task_proof),
    path("courier/tasks/", views.courier_my_tasks),
    path("courier/tasks/<int:task_id>/status/", views.courier_update_task_status),
    path("courier/tasks/<int:task_id>/assign/", views.assign_courier_task),
    path("referrals/", views.referrals),
    path("referrals/create/", views.create_referral),
    # Согласование подарка дистрибьютором (п. 7 ТЗ).
    path("referrals/pending-gifts/", views.distributor_referral_gifts),
    path("referrals/<int:referral_id>/decide-gift/", views.decide_referral_gift),
    # Обучающие материалы (п. 10 ТЗ).
    path("learning-materials/", views.learning_materials),
    path("tickets/", views.tickets),
    path("tickets/create/", views.create_ticket),
    path("tickets/<int:ticket_id>/expert-answer/", views.expert_answer_ticket),
    path("knowledge-cards/", views.knowledge_cards),
    path("knowledge-cards/create/", views.create_knowledge_card),
    path("knowledge-cards/<int:card_id>/update/", views.update_knowledge_card),
    path("regions/", views.regions),
    path("distributors/", views.distributors),
    path("debug/push/", views.push_diagnostics),
    path("notifications/", views.notifications),
    path("notifications/read/", views.mark_notifications_read),
    path("notifications/send/", views.send_notification),
    path("notifications/token/", views.register_device_token),
    path("ai/chat/", views.ai_chat),
]
