from django.urls import path

from . import schema, views

urlpatterns = [
    path("docs/", schema.swagger_ui),
    path("schema/", schema.openapi_schema),
    path("health/", views.health),
    path("register/", views.register),
    path("auth/register/", views.register),
    path("login/", views.login),
    path("auth/me/", views.me),
    path("dashboard/", views.dashboard),
    path("stores/", views.stores),
    path("products/", views.products),
    path("order-config/", views.order_config),
    path("orders/", views.orders),
    path("orders/create/", views.create_order),
    path("purchases/", views.purchases),
    path("purchases/create/", views.create_purchase),
    path("distributor/dashboard/", views.distributor_dashboard),
    path("distributor/clients/", views.distributor_clients),
    path("distributor/purchases/", views.distributor_purchases),
    path("distributor/purchases/<int:purchase_id>/verify/", views.distributor_verify_purchase),
    path("distributor/orders/", views.distributor_orders),
    path("distributor/orders/<int:order_id>/status/", views.distributor_update_order_status),
    path("distributor/stock/", views.distributor_stock),
    path("distributor/stock/upload/", views.distributor_stock_upload),
    path("distributor/reports/", views.distributor_reports),
    path("color-requests/", views.color_requests),
    path("color-requests/create/", views.create_color_request),
    path("courier-tasks/", views.courier_tasks),
    path("courier-tasks/create/", views.create_courier_task),
    path("courier-tasks/<int:task_id>/proof/", views.courier_task_proof),
    path("courier/tasks/", views.courier_my_tasks),
    path("courier/tasks/<int:task_id>/status/", views.courier_update_task_status),
    path("courier/tasks/<int:task_id>/assign/", views.assign_courier_task),
    path("referrals/", views.referrals),
    path("referrals/create/", views.create_referral),
    path("tickets/", views.tickets),
    path("tickets/create/", views.create_ticket),
    path("tickets/<int:ticket_id>/expert-answer/", views.expert_answer_ticket),
    path("knowledge-cards/", views.knowledge_cards),
    path("knowledge-cards/<int:card_id>/update/", views.update_knowledge_card),
    path("regions/", views.regions),
    path("notifications/", views.notifications),
    path("notifications/read/", views.mark_notifications_read),
    path("ai/chat/", views.ai_chat),
]
